export const UI = {
  en: {
    title: "FIGARO.LABS",
    tagline: "Networking Intelligence Studio",
    dashboard: "Dashboard",
    mindMap: "Mind Map",
    resources: "Resources",
    progress: "Progress",
    search: "Search concepts",
    focus: "Focus",
    overview: "Overview",
    upgrade: "Upgrade",
    usage: "Monthly usage",
    plan: "Your plan",
    pro: "Pro",
    enterprise: "Enterprise",
    schedule: "Schedule",
    knowledge: "Knowledge",
    quickActions: "Quick Actions",
    language: "Language",
    aiSummary: "AI Summaries",
    insights: "Learning Insights",
    progressText: "Learning momentum",
    focusMode: "Focus mode",
    explore: "Explore",
    startTrial: "Start free trial",
    subscribe: "Subscribe",
    billing: "Subscription",
    benefitTitle: "Commercial-ready learning experience",
    noteTitle: "Arabic support",
    noteBody: "Instant RTL layout and bilingual labels for global reach.",
    lecture: "Lecture",
    selectLecture: "Select lecture",
    quiz: "Quiz",
    flashcards: "Flashcards",
    answer: "Answer",
    quizTitle: "Quiz questions",
    flashcardsTitle: "Flashcards",
    studyFromMap: "Generated from this lecture's mind map.",
    dashboardIntro: "Pick a lecture to open the interactive mind map and start studying.",
    openMindMap: "Open mind map",
    studyArea: "Study area"
  },
  ar: {
    title: "فيغارو لابس",
    tagline: "استوديو ذكاء الشبكات",
    dashboard: "لوحة التحكم",
    mindMap: "الخريطة الذهنية",
    resources: "الموارد",
    progress: "التقدم",
    search: "ابحث عن المفاهيم",
    focus: "تركيز",
    overview: "نظرة عامة",
    upgrade: "ترقية",
    usage: "الاستخدام الشهري",
    plan: "خطتك",
    pro: "محترف",
    enterprise: "مؤسسي",
    schedule: "الجدول",
    knowledge: "المعرفة",
    quickActions: "إجراءات سريعة",
    language: "اللغة",
    aiSummary: "ملخصات الذكاء الاصطناعي",
    insights: "رؤى التعلم",
    progressText: "زخم التعلم",
    focusMode: "وضع التركيز",
    explore: "استكشف",
    startTrial: "ابدأ التجربة المجانية",
    subscribe: "اشترك",
    billing: "الاشتراك",
    benefitTitle: "تجربة تعلم جاهزة للاستخدام التجاري",
    noteTitle: "دعم اللغة العربية",
    noteBody: "تخطيط من اليمين لليسار وترجمات ثنائية لانتشار عالمي.",
    lecture: "المحاضرة",
    selectLecture: "اختر المحاضرة",
    quiz: "اختبار",
    flashcards: "بطاقات",
    answer: "الإجابة",
    quizTitle: "أسئلة الاختبار",
    flashcardsTitle: "بطاقات المراجعة",
    studyFromMap: "تم توليدها من الخريطة الذهنية لهذه المحاضرة.",
    dashboardIntro: "اختر محاضرة لفتح الخريطة الذهنية والبدء في المذاكرة.",
    openMindMap: "افتح الخريطة",
    studyArea: "مساحة الدراسة"
  }
};
